FROM python:3.11-slim

RUN mkdir -p /app

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY ./app.py /app/app.py

WORKDIR /app

CMD gunicorn -b 0.0.0.0:8050 app:server --timeout 90